// Generated by CoffeeScript 1.4.0
var dp, log,
  __slice = [].slice;

dp = require('docpad');

log = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return console.log.apply(console, args);
};

console.log(dp);
